services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/database.sqlite:/app/database.sqlite

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend